### ISSUE TITLE
 PHP code action does not activate

### ISSUE THREAD

**Issue by IagoParisDev** [rioj7/my-code-actions#3]
Hello, I have designed a code action in php, but it does not appear, instead, I have this:
![my code actions problem](https://user-images.githubusercontent.com/109851533/181209443-d821430c-479e-4029-816d-e630ebfee790.png)

I simplified the code action to see if it was a regex not matching, but that showed before keeps happening. This is the current code action:
```JSON
"my-code-actions.actions": {
    "[php]": {
      "Add literal A to lang files": {
        "diagnostics": ["Undefined class constant.*"],
        "atCursor": "RPLC",
        "file": "/profe.com/lang/lang_es_ES.ini",
        "where": "start",
        "insertFind": "",
        "text": "{{diag:$1}} = {{atCursor:$1}}\n"
      }
    },
  }
```

What is the problem?

**Comment by rioj7** [comment]
@IagoParisDev  Can you get it to work with the simplest action description:

```
"my-code-actions.actions": {
    "[php]": {
      "Add literal Hello to current file": {
        "diagnostics": ["Undefined class constant '(.*?)'"],
        "text": "Hello\n"
      }
    }
  }
```

Why do you reference capture groups in your `text` but you don't have capture groups in the `diagnostics` and `atCursor` properties

**Comment by IagoParisDev** [comment]
Oh, it works! Thank you for your quick response :)

To answer your question, I removed the capture groups to simplify the code, but forgot to remove also de references.

I've built progressively from there to find where it stops working. This is the intended final code action:

```JSON  
  "my-code-actions.actions": {
    "[php]": {
      "Add literal '{{diag:$1}}' to lang files": {
        "diagnostics": [
          "Undefined class constant '(.*?)'"
        ],
        "atCursor": "; \\?>(.+)(<|\"|')",
        "edits": [
          {
            "file": "/profe.com/lang/lang_es_ES.ini",
            "where": "start",
            "text": "{{diag:$1}} = \"{{atCursor:$1}}\"\n"
          },
          {
            "file": "/profe.com/lang/lang_ca_ES.ini",
            "where": "start",
            "text": "{{diag:$1}} = \"{{atCursor:$1}}\"\n"
          },
          {
            "file": "/profe.com/lang/lang_en_GB.ini",
            "where":"start",
            "text": "{{diag:$1}} = \"{{atCursor:$1}}\"\n"
          }
        ]
      }
    }
  }
```

I have found that adding the field `atCursor:` is the problem, the quick fix does not appear then, I have tried different regex like ";" or "(.*)" without success. Every other field works as intended.

**Comment by rioj7** [comment]
@IagoParisDev The confusion is probably "where is the cursor position" that is used for the `atCursor` regex search.

Because you have a diagnostic (entry in PROBLEMS panel) you can call the action from the PROBLEMS panel. The cursor can be anywhere in the file. To be consistent in the file location the program uses the start of the diagnostic squiggle. If the position does not fall inside a match or is at the edge of the match for the  `atCursor` regex you don't get an action.

Try the following:

```
"atCursor": "\\w+;\\s*\\?>([^<\"']+)"
```

You can place the `\w` in a capture group and only use `{{atCursor:$n}}` fields.

At the moment not possible but better would be:

```
"atCursor": "{{diag:$1}};\\s*\\?>([^<\"']+)"
```

The diagnostic is already a match so its capture groups could be used in the `atCursor` regex.

I will add clarification for the cursor position.

**Comment by IagoParisDev** [comment]
Oh, I understand now! And your code proposal works!

Thank you very much! Also thanks for the regex restructuration! :D

**Comment by rioj7** [comment]
@IagoParisDev with v1.0.0 you can use

```
"atCursor": "{{diag:$1}};\\s*\\?>([^<\"']+)"
```
