### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by kitbdev** [rioj7/my-code-actions#6]
The extension fails does not show any Code Actions.

Extension Host output:
[error] [rioj7.my-code-actions] provider FAILED
[error] TypeError: Cannot read properties of undefined (reading 'replace')
	at evalFields (c:\Users\kit\.vscode\extensions\rioj7.my-code-actions-1.0.0\my-code-actions.js:301:15)

Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by rioj7** [comment]
@kitbdev  You don't get this error with an empty setting.

Without the `my-code-actions.actions` setting that you use I have no clue what the reason is.

Maybe also needed example file(s) content that is used.

**Comment by kitbdev** [comment]
Any setting that is not empty has this error.
for instance, this from the example:
```
    "my-code-actions.actions": {
        "[c,cpp]": {
          "include stdio": { "text": "#include <stdio.h>\n" },
        },
    },
```
this happens in any file with language mode set to cpp, including an empty file

same with python
```
    "my-code-actions.actions": {
        "[python]": {
          "test": { },
        },
    },
```
file: test.py
```
print("test")
```

I also tried the example in the readme, same issue. (btw, the example is missing a '}' after the php block)

**Comment by rioj7** [comment]
@kitbdev Can you try v1.0.1?

Thanks for the README typo, caused by a copy/paste from the `settings.json`, but including the close `}` because of not selecting the junk after the rules I want.

----

I'm stumped that this error has been there from the start, I have tested many examples but probably not the simplest.

You showed a stack trace in the question only 1 deep, that made it a bit more difficult to locate the caller of that function.

It can make it easier to show all the lines of the top of the stack trace that relate to the extension (not the VSC main stuff)

For this case it would look like:

```none
ERR Cannot read property 'replace' of undefined: TypeError: Cannot read property 'replace' of undefined
	at evalFields (c:\Users\kit.vscode\extensions\rioj7.my-code-actions-1.0.0\my-code-actions.js:301:15)
	at QuickFix.provideCodeActions (c:\Users\kit.vscode\extensions\rioj7.my-code-actions-1.0.0\my-code-actions.js:353:20)
	at LanguageCodeActionProvider.provideCodeActions (c:\Users\kit.vscode\extensions\rioj7.my-code-actions-1.0.0\my-code-actions.js:59:42)
```

**Comment by kitbdev** [comment]
Thanks, it's working now!
Sorry about the short stack trace.
